# Base configs
baseurl: /profileflat

# UI configs
title: "Rajput Shubham"
author: "Rajput Shubham"
about: "A Pythonista"
social_urls:
  facebook: "https://www.facebook.com/shubhamrajput262"
  twitter: "https://www.twitter.com/mistryvatsal11"
  instagram: "https://www.instagram.com/she_calls_me_sweetu"
